
name: Docker Build

on:
  workflow_call:
    inputs:
      push:
        description: 'should push image to ghcr.io'
        default: false
        required: false
        type: boolean
    outputs:
      image:
        description: "the built docker image name"
        value: ${{ jobs.docker.outputs.image }}

jobs:
  docker:
    name: Build docker image and optionally push to GitHub Container Registry
    runs-on: ubuntu-latest
    outputs:
      image: ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.version }}
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=edge
            type=sha
            type=ref,event=pr
      - name: Login to GitHub Container Registry
        if: ${{ inputs.push == true }}
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
