name: Docker Publish

# --- Example Usage ---
# on:
#   push:
#     branches:
#       - main
#     tags:
#       - 'v*.*.*'
# jobs:
#   example:
#     - uses: benfrisbie/workflows/.github/workflows/docker/publish.yml@main

on:
  workflow_call:

jobs:
  docker-publish:
    name: Build docker image and push to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=edge
            type=sha
      - name: Login to GitHub Container Registry
        if: ${{ inputs.push == true }}
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
