name: Docker

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    paths:
      - 'Dockerfile'
      - 'requirements.txt'
      - 'src/**'

jobs:
  example:
    uses: AptivConnectedServices/public-workflows/.github/workflows/docker.yml@main
    with:
      name: ${{ github.repository }}
      push: ${{ github.event_name == 'push' }}
