name: Docker

# --- Example Usage ---
# name: Docker
# on:
#   push:
#     branches:
#       - main
#     tags:
#       - 'v*.*.*'
#   pull_request:
#     paths:
#       - 'Dockerfile'
# jobs:
#   example:
#     uses: benfrisbie/workflows/.github/workflows/docker.yml@main
#     with:
#       push: false

on:
  workflow_call:
    inputs:
      push:
        type: boolean
        required: false
        default: false
        description: 'push image to ghcr.io'

jobs:
  docker:
    name: Build docker image and optionally push to ghcr.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=edge
            type=sha
      - name: Login to GitHub Container Registry
        if: ${{ inputs.push == true }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ inputs.push == true }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
